In [2]:
import numpy as np

In [3]:
import random

In [50]:
a1 = []
for i in range(20):
    a1.append(random.randint(1, 100))

In [51]:
len(a1)

20

In [22]:
ar1 = np.arange(1, 21)


In [53]:
ar1+a1

array([ 60,  74,  80,  42,  65, 101,  92,  65,  56,  86,  36,  85,  89,
        68,  41,  18, 110,  41,  68,  99])

In [54]:
ar1-a1

array([-58, -70, -74, -34, -55, -89, -78, -49, -38, -66, -14, -61, -63,
       -40, -11,  14, -76,  -5, -30, -59])

In [55]:
ar1*a1

array([  59,  144,  231,  152,  300,  570,  595,  456,  423,  760,  275,
        876,  988,  756,  390,   32, 1581,  414,  931, 1580])

In [56]:
ar1/a1

array([0.01694915, 0.02777778, 0.03896104, 0.10526316, 0.08333333,
       0.06315789, 0.08235294, 0.14035088, 0.19148936, 0.13157895,
       0.44      , 0.16438356, 0.17105263, 0.25925926, 0.57692308,
       8.        , 0.1827957 , 0.7826087 , 0.3877551 , 0.25316456])

In [73]:
list_1 = []
for j in range(4):
    list_2 = []
    for i in range(5):
        list_2.append(random.randint(1, 100))
    list_1.append(list_2)

In [76]:
list_1

[[46, 50, 80, 6, 75],
 [70, 81, 41, 45, 18],
 [13, 87, 42, 55, 40],
 [75, 86, 91, 16, 96]]

In [84]:
print(len(list_1)) # Вывод количесва строчек
print(len(list_1[0])) # Вывод количесва столбиков
for i in range(len(list_1)):
    print(list_1[i]) # Вывод всего масива
print('______________________________________')
for i in range(len(list_1)):
    print('Вывод максимальных чисел по строчкам')
    print(max(list_1[i]))
print('______________________________________')
for i in range(len(list_1[0])):
    print('Максимальные в слобе', i)
    print(max(list_1[0][i], list_1[1][i], list_1[2][i], list_1[3][i]))

4
5
[46, 50, 80, 6, 75]
[70, 81, 41, 45, 18]
[13, 87, 42, 55, 40]
[75, 86, 91, 16, 96]
______________________________________
Вывод максимальных чисел по строчкам
80
Вывод максимальных чисел по строчкам
81
Вывод максимальных чисел по строчкам
87
Вывод максимальных чисел по строчкам
96
______________________________________
Максимальные в слобе 0
75
Максимальные в слобе 1
87
Максимальные в слобе 2
91
Максимальные в слобе 3
55
Максимальные в слобе 4
96


In [86]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [87]:
np.max(ar1)

20

In [90]:
ar1.shape = 4, 5 

In [91]:
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])